server:
  port: 8086

# when app is running on host
# spring.datasource.url=jdbc:mysql://localhost:3306/petclinic
# when app is running in docker

spring:
  datasource:
      url: ${DB_URL}
      username: ${DB_USER_NAME}
      password: ${DB_PWD}

  jpa:
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: localhost
      port: 6379


logging:
  level:
    org.springframework.cache.*: trace





#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

# spring.application.name=PetClinic-APP
# eureka.client.register-with-eureka=true
# service-url=http://localhost:8761/eureka
# if app is running in docker
# service-url=http://host.docker.internal:8761/eureka

